# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_auto_20170830_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upload',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
